---
title: "Kvalitetskontroll del 2: compare"
author: ""
date: "`r Sys.Date()`"
output:
  html_document: 
    df_print: paged
    toc: true
    toc_float: true
---
For more info about the quality control, see [here](https://github.com/helseprofil/KHvalitetskontroll)!

```{r setup, include=FALSE}
# Global settings, do not change
knitr::opts_chunk$set(cache = F, echo = F)
source("https://raw.githubusercontent.com/helseprofil/KHvalitetskontroll/main/R/setup.R")
#source("../R/functions_step2.R")
```

# INPUT

**Data files loaded**
```{r echo = F}
## Load data
dfnew <- ReadFile(file = "HKR", # Matching, if >1 file found in folder, specify file name further
                  modus = "KH", # KH or NH
                  folder = 2023) # "DATERT" or 4-digit year if file in NESSTAR-folder

dfold <- ReadFile(file = "HKR", # Matching, if >1 file found in folder, specify file name further
                  modus = "KH",# KH or NH
                  folder = 2022) # DATERT" or 4-digit year if file in NESSTAR-folder
```
```{r}
####
# To get a list of variable names in the new and old KUBE, run the following code
names(dfnew)
names(dfold)
###

# Define all dimensions used to identify new or expired rows in the two KUBEs
DIMENSIONS <- c("GEO", "AAR", "KJONN", "ALDER", "KODEGRUPPE")

# Define all value columns to be compared between the two KUBEs
VALUES <- c("TELLER", "RATE", "SMR", "MEIS", "RATE.n", "sumTELLER", "sumNEVNER")

# If you want to save .csv-files of the flagged KUBEs, define 
# Available options: "dfnew_flag", "dfold_flag"
# For no dumps, replace with "DUMPS <- NULL"
DUMPS <- c("dfnew_flag")
DUMPname <- "HKR" # NAME of KUBE, for naming of dumps
```

```{r}
# To print input, do not change:
cat("DIMENSION columns: ", print_dim(DIMENSIONS), 
    "\nVALUE columns: ", print_dim(VALUES))
```
# Flag all new rows in new KUBE

- According to strata defined by the following dimensions: `r print_dim(DIMENSIONS)`
    - Flags all **new** rows in the new KUBE (strata not present in old KUBE)
    - Flags all **expired** rows in the old KUBE (strata not present in the new KUBE)
- Create flagged versions of KUBES

```{r}
FormatData()
```

```{r}
dfnew_flag[newrow == 0][dfold_flag[exprow == 0], on = VALUES]
```

```{r}

  dimnew <- names(dfnew[, names(dfnew) %in% DIMENSIONS, with = F])
  dimold <- names(dfold[, names(dfold) %in% DIMENSIONS, with = F])
  commondims <- dimnew[dimnew %in% dimold]
  newdims <- dimnew[!dimnew %in% dimold]
  expdims <- dimold[!dimold %in% dimnew]
  valnew <- names(dfnew[, names(dfnew) %in% VALUES, with = F])
  valold <- names(dfold[, names(dfold) %in% VALUES, with = F])
  commonvals <- valnew[valnew %in% valold]
  newvals <- valnew[!valnew %in% valold]
  expvals <- valold[!valold %in% valnew]



comparedata <- function(data1 = dfnew_flag,
                        data2 = dfold_flag,
                        dims = commondims,
                        vals = commonvals){
  
  
  # Format new KUBE
  cat("\n-Formats new KUBE")
  cat("\n  -Remove new rows, select common dimensions and values")
  comparenew <- copy(data1)
  # Remove new rows, select common columns and values
  comparenew <- comparenew[newrow == 0,
                           c(commondims, commonvals), with = F]
  # Add suffix to value columns
  commonvals_new <- paste0(commonvals, "_new")
  setnames(comparenew, commonvals, commonvals_new)
  
  # Format old KUBE
  cat("\n-Formats old KUBE")
  cat("\n  -Remove expired rows, select common dimensions and values")
  compareold <- copy(data2)
  # Remove new rows, select common columns and values
  compareold <- compareold[exprow == 0,
                           c(commondims, commonvals), with = F]
  # Add suffix to value columns
  commonvals_old <- paste0(commonvals, "_old")
  setnames(compareold, commonvals, commonvals_old)
  
  # Create comparedata
  compareKUBE <<- comparenew[compareold, on = commondims]
  
}
  
  
comparedata()
comparenew
```


